services:
  spring-app:
    image: openjdk:17-jdk
    container_name: smart-core-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9094:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12341234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-tracker-net

  postgres:
    image: 'postgres:13-alpine3.17'
    container_name: postgres
    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5432:5432"
    networks:
      - task-tracker-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  task-tracker-net:
    driver: bridge
