spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: my-secure-random-secret-key-for-signing
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 30
  mail:
    host: smtp.yandex.ru
    port: 587
    username: danvoropaeff@yandex.ru
    password: dlsozlyictdqaaqv
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        starttls.required: true
        smtp.ssl.trust: smtp.yandex.ru

